overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-xlsxr.yml
targets:
  - README.rst: custom_readme.rst.jj2
  - setup.py: custom_setup.py.jj2
  - "pyexcel_xlsxr/_version.py": version.py.jj2
